export interface BDFood {
  id: string
  name_en: string
  name_bn: string
  calories_per_100g: number
  protein_g: number
  carbs_g: number
  fat_g: number
  iron_mg: number
  calcium_mg: number
  folate_mcg: number
  season: ('all' | 'winter' | 'summer' | 'monsoon')[]
  divisions: ('all' | 'Dhaka' | 'Chattogram' | 'Rajshahi' | 'Khulna' | 'Sylhet' | 'Barishal' | 'Rangpur' | 'Mymensingh')[]
  price_tier: 'low' | 'mid' | 'premium'
  good_for: ('pregnancy' | 'anaemia' | 'diabetes' | 'hypertension' | 'child' | 'adolescent' | 'general')[]
  avoid_for: ('diabetes' | 'hypertension' | 'kidney' | 'gout')[]
}

export const BD_FOODS: BDFood[] = [
  {
    id: 'rice',
    name_en: 'Rice (cooked)',
    name_bn: 'ভাত',
    calories_per_100g: 130,
    protein_g: 2.7,
    carbs_g: 28,
    fat_g: 0.3,
    iron_mg: 0.2,
    calcium_mg: 10,
    folate_mcg: 8,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general', 'child', 'adolescent'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'roti',
    name_en: 'Whole Wheat Roti',
    name_bn: 'রুটি',
    calories_per_100g: 297,
    protein_g: 9,
    carbs_g: 57,
    fat_g: 3.7,
    iron_mg: 3.5,
    calcium_mg: 34,
    folate_mcg: 22,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'general', 'adolescent'],
    avoid_for: [],
  },
  {
    id: 'dal',
    name_en: 'Lentil Dal',
    name_bn: 'ডাল',
    calories_per_100g: 116,
    protein_g: 9,
    carbs_g: 20,
    fat_g: 0.4,
    iron_mg: 3.3,
    calcium_mg: 19,
    folate_mcg: 181,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'general', 'child', 'adolescent'],
    avoid_for: ['kidney', 'gout'],
  },
  {
    id: 'hilsa',
    name_en: 'Hilsa Fish',
    name_bn: 'ইলিশ মাছ',
    calories_per_100g: 273,
    protein_g: 21,
    carbs_g: 0,
    fat_g: 19,
    iron_mg: 2.2,
    calcium_mg: 180,
    folate_mcg: 15,
    season: ['monsoon'],
    divisions: ['Barishal', 'Khulna', 'Dhaka', 'Chattogram'],
    price_tier: 'premium',
    good_for: ['pregnancy', 'general', 'adolescent'],
    avoid_for: [],
  },
  {
    id: 'rohu',
    name_en: 'Rohu Fish',
    name_bn: 'রুই মাছ',
    calories_per_100g: 97,
    protein_g: 16.6,
    carbs_g: 0,
    fat_g: 2.7,
    iron_mg: 1.0,
    calcium_mg: 650,
    folate_mcg: 10,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'mid',
    good_for: ['pregnancy', 'anaemia', 'child', 'general'],
    avoid_for: [],
  },
  {
    id: 'chicken',
    name_en: 'Chicken (skinless)',
    name_bn: 'মুরগির মাংস',
    calories_per_100g: 165,
    protein_g: 31,
    carbs_g: 0,
    fat_g: 3.6,
    iron_mg: 1.3,
    calcium_mg: 15,
    folate_mcg: 4,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'mid',
    good_for: ['pregnancy', 'anaemia', 'child', 'adolescent', 'general'],
    avoid_for: [],
  },
  {
    id: 'egg',
    name_en: 'Egg',
    name_bn: 'ডিম',
    calories_per_100g: 155,
    protein_g: 13,
    carbs_g: 1.1,
    fat_g: 11,
    iron_mg: 1.8,
    calcium_mg: 56,
    folate_mcg: 47,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'child', 'adolescent', 'general'],
    avoid_for: [],
  },
  {
    id: 'spinach',
    name_en: 'Spinach (Palak)',
    name_bn: 'পালং শাক',
    calories_per_100g: 23,
    protein_g: 2.9,
    carbs_g: 3.6,
    fat_g: 0.4,
    iron_mg: 2.7,
    calcium_mg: 99,
    folate_mcg: 194,
    season: ['winter'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'diabetes', 'hypertension', 'general'],
    avoid_for: ['kidney', 'gout'],
  },
  {
    id: 'bottle_gourd',
    name_en: 'Bottle Gourd (Lau)',
    name_bn: 'লাউ',
    calories_per_100g: 15,
    protein_g: 0.6,
    carbs_g: 3.4,
    fat_g: 0.1,
    iron_mg: 0.2,
    calcium_mg: 26,
    folate_mcg: 6,
    season: ['summer', 'monsoon'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'hypertension', 'general', 'pregnancy'],
    avoid_for: [],
  },
  {
    id: 'bitter_melon',
    name_en: 'Bitter Melon (Karela)',
    name_bn: 'করলা',
    calories_per_100g: 17,
    protein_g: 1,
    carbs_g: 3.7,
    fat_g: 0.2,
    iron_mg: 0.4,
    calcium_mg: 19,
    folate_mcg: 72,
    season: ['summer', 'monsoon'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'general'],
    avoid_for: [],
  },
  {
    id: 'pumpkin',
    name_en: 'Pumpkin (Kumra)',
    name_bn: 'কুমড়া',
    calories_per_100g: 26,
    protein_g: 1,
    carbs_g: 6.5,
    fat_g: 0.1,
    iron_mg: 0.8,
    calcium_mg: 21,
    folate_mcg: 16,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'child', 'general'],
    avoid_for: [],
  },
  {
    id: 'sweet_potato',
    name_en: 'Sweet Potato (Misti Alu)',
    name_bn: 'মিষ্টি আলু',
    calories_per_100g: 86,
    protein_g: 1.6,
    carbs_g: 20,
    fat_g: 0.1,
    iron_mg: 0.6,
    calcium_mg: 30,
    folate_mcg: 11,
    season: ['winter'],
    divisions: ['Rangpur', 'Mymensingh', 'Rajshahi'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'child', 'general'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'banana',
    name_en: 'Banana (Kola)',
    name_bn: 'কলা',
    calories_per_100g: 89,
    protein_g: 1.1,
    carbs_g: 23,
    fat_g: 0.3,
    iron_mg: 0.3,
    calcium_mg: 5,
    folate_mcg: 20,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'child', 'adolescent', 'general'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'papaya',
    name_en: 'Papaya (Pepe)',
    name_bn: 'পেঁপে',
    calories_per_100g: 43,
    protein_g: 0.5,
    carbs_g: 11,
    fat_g: 0.3,
    iron_mg: 0.3,
    calcium_mg: 20,
    folate_mcg: 37,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['anaemia', 'general', 'adolescent'],
    avoid_for: [],
  },
  {
    id: 'jackfruit',
    name_en: 'Jackfruit (Kathal)',
    name_bn: 'কাঁঠাল',
    calories_per_100g: 95,
    protein_g: 1.7,
    carbs_g: 23,
    fat_g: 0.6,
    iron_mg: 0.6,
    calcium_mg: 24,
    folate_mcg: 24,
    season: ['summer'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general', 'child', 'adolescent'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'mango',
    name_en: 'Mango (Aam)',
    name_bn: 'আম',
    calories_per_100g: 60,
    protein_g: 0.8,
    carbs_g: 15,
    fat_g: 0.4,
    iron_mg: 0.2,
    calcium_mg: 11,
    folate_mcg: 43,
    season: ['summer'],
    divisions: ['Rajshahi', 'Khulna', 'Dhaka'],
    price_tier: 'low',
    good_for: ['pregnancy', 'child', 'general'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'guava',
    name_en: 'Guava (Peyara)',
    name_bn: 'পেয়ারা',
    calories_per_100g: 68,
    protein_g: 2.6,
    carbs_g: 14,
    fat_g: 1,
    iron_mg: 0.3,
    calcium_mg: 18,
    folate_mcg: 49,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'hypertension', 'general', 'pregnancy'],
    avoid_for: [],
  },
  {
    id: 'lichi',
    name_en: 'Lychee (Lichu)',
    name_bn: 'লিচু',
    calories_per_100g: 66,
    protein_g: 0.8,
    carbs_g: 17,
    fat_g: 0.4,
    iron_mg: 0.3,
    calcium_mg: 5,
    folate_mcg: 14,
    season: ['summer'],
    divisions: ['Rajshahi', 'Rangpur', 'Mymensingh'],
    price_tier: 'mid',
    good_for: ['general', 'child'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'coconut',
    name_en: 'Coconut (Narkel)',
    name_bn: 'নারকেল',
    calories_per_100g: 354,
    protein_g: 3.3,
    carbs_g: 15,
    fat_g: 33,
    iron_mg: 2.4,
    calcium_mg: 14,
    folate_mcg: 26,
    season: ['all'],
    divisions: ['Chattogram', 'Barishal', 'Khulna'],
    price_tier: 'low',
    good_for: ['general', 'pregnancy'],
    avoid_for: ['hypertension'],
  },
  {
    id: 'milk',
    name_en: 'Cow Milk',
    name_bn: 'গরুর দুধ',
    calories_per_100g: 61,
    protein_g: 3.2,
    carbs_g: 4.8,
    fat_g: 3.3,
    iron_mg: 0.1,
    calcium_mg: 113,
    folate_mcg: 5,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'mid',
    good_for: ['pregnancy', 'child', 'adolescent', 'general'],
    avoid_for: [],
  },
  {
    id: 'yogurt',
    name_en: 'Yogurt (Doi)',
    name_bn: 'দই',
    calories_per_100g: 59,
    protein_g: 3.5,
    carbs_g: 5,
    fat_g: 3.3,
    iron_mg: 0.1,
    calcium_mg: 121,
    folate_mcg: 7,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'mid',
    good_for: ['diabetes', 'pregnancy', 'general'],
    avoid_for: [],
  },
  {
    id: 'paneer',
    name_en: 'Paneer (Chhana)',
    name_bn: 'ছানা',
    calories_per_100g: 265,
    protein_g: 18,
    carbs_g: 3.4,
    fat_g: 20,
    iron_mg: 0.5,
    calcium_mg: 480,
    folate_mcg: 18,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'mid',
    good_for: ['pregnancy', 'child', 'general'],
    avoid_for: [],
  },
  {
    id: 'mustard_oil',
    name_en: 'Mustard Oil (Sariser Tel)',
    name_bn: 'সরিষার তেল',
    calories_per_100g: 884,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 100,
    iron_mg: 0,
    calcium_mg: 0,
    folate_mcg: 0,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general'],
    avoid_for: ['hypertension'],
  },
  {
    id: 'ghee',
    name_en: 'Ghee',
    name_bn: 'ঘি',
    calories_per_100g: 900,
    protein_g: 0,
    carbs_g: 0,
    fat_g: 100,
    iron_mg: 0,
    calcium_mg: 0,
    folate_mcg: 0,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'premium',
    good_for: ['pregnancy', 'child'],
    avoid_for: ['hypertension', 'diabetes'],
  },
  {
    id: 'turmeric',
    name_en: 'Turmeric (Holud)',
    name_bn: 'হলুদ',
    calories_per_100g: 312,
    protein_g: 9.7,
    carbs_g: 67,
    fat_g: 3.2,
    iron_mg: 41.4,
    calcium_mg: 168,
    folate_mcg: 20,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general', 'anaemia'],
    avoid_for: [],
  },
  {
    id: 'ginger',
    name_en: 'Ginger (Ada)',
    name_bn: 'আদা',
    calories_per_100g: 80,
    protein_g: 1.8,
    carbs_g: 18,
    fat_g: 0.8,
    iron_mg: 0.6,
    calcium_mg: 16,
    folate_mcg: 11,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general', 'pregnancy'],
    avoid_for: [],
  },
  {
    id: 'garlic',
    name_en: 'Garlic (Roshun)',
    name_bn: 'রসুন',
    calories_per_100g: 149,
    protein_g: 6.4,
    carbs_g: 33,
    fat_g: 0.5,
    iron_mg: 1.7,
    calcium_mg: 181,
    folate_mcg: 3,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['hypertension', 'general'],
    avoid_for: [],
  },
  {
    id: 'onion',
    name_en: 'Onion (Piyaj)',
    name_bn: 'পেঁয়াজ',
    calories_per_100g: 40,
    protein_g: 1.1,
    carbs_g: 9.3,
    fat_g: 0.1,
    iron_mg: 0.2,
    calcium_mg: 23,
    folate_mcg: 19,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['general', 'hypertension'],
    avoid_for: [],
  },
  {
    id: 'tomato',
    name_en: 'Tomato (Tamato)',
    name_bn: 'টমেটো',
    calories_per_100g: 18,
    protein_g: 0.9,
    carbs_g: 3.9,
    fat_g: 0.2,
    iron_mg: 0.3,
    calcium_mg: 10,
    folate_mcg: 15,
    season: ['winter'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['hypertension', 'general', 'pregnancy'],
    avoid_for: [],
  },
  {
    id: 'carrot',
    name_en: 'Carrot (Gajor)',
    name_bn: 'গাজর',
    calories_per_100g: 41,
    protein_g: 0.9,
    carbs_g: 10,
    fat_g: 0.2,
    iron_mg: 0.3,
    calcium_mg: 33,
    folate_mcg: 19,
    season: ['winter'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'child', 'general'],
    avoid_for: [],
  },
  {
    id: 'cauliflower',
    name_en: 'Cauliflower (Phulkopi)',
    name_bn: 'ফুলকপি',
    calories_per_100g: 25,
    protein_g: 1.9,
    carbs_g: 5,
    fat_g: 0.3,
    iron_mg: 0.4,
    calcium_mg: 22,
    folate_mcg: 57,
    season: ['winter'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'general', 'pregnancy'],
    avoid_for: ['kidney', 'gout'],
  },
  {
    id: 'brinjal',
    name_en: 'Brinjal / Eggplant (Begun)',
    name_bn: 'বেগুন',
    calories_per_100g: 25,
    protein_g: 1,
    carbs_g: 6,
    fat_g: 0.2,
    iron_mg: 0.2,
    calcium_mg: 9,
    folate_mcg: 22,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'general'],
    avoid_for: [],
  },
  {
    id: 'okra',
    name_en: 'Okra / Ladies Finger (Dherosh)',
    name_bn: 'ঢেঁড়স',
    calories_per_100g: 33,
    protein_g: 1.9,
    carbs_g: 7.5,
    fat_g: 0.2,
    iron_mg: 0.6,
    calcium_mg: 82,
    folate_mcg: 60,
    season: ['summer', 'monsoon'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['diabetes', 'pregnancy', 'general'],
    avoid_for: ['kidney', 'gout'],
  },
  {
    id: 'drumstick',
    name_en: 'Drumstick (Shojne)',
    name_bn: 'সজনে',
    calories_per_100g: 37,
    protein_g: 2.1,
    carbs_g: 8.5,
    fat_g: 0.2,
    iron_mg: 4,
    calcium_mg: 30,
    folate_mcg: 44,
    season: ['summer'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'general'],
    avoid_for: [],
  },
  {
    id: 'moringa',
    name_en: 'Moringa Leaves (Shojne Pata)',
    name_bn: 'সজনে পাতা',
    calories_per_100g: 64,
    protein_g: 9.4,
    carbs_g: 8.3,
    fat_g: 1.4,
    iron_mg: 4,
    calcium_mg: 185,
    folate_mcg: 40,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'child', 'general'],
    avoid_for: [],
  },
  {
    id: 'date_khejur',
    name_en: 'Date (Khejur)',
    name_bn: 'খেজুর',
    calories_per_100g: 277,
    protein_g: 1.8,
    carbs_g: 75,
    fat_g: 0.2,
    iron_mg: 0.9,
    calcium_mg: 64,
    folate_mcg: 15,
    season: ['winter'],
    divisions: ['Rajshahi', 'Khulna'],
    price_tier: 'mid',
    good_for: ['anaemia', 'pregnancy', 'general'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'black_sesame',
    name_en: 'Black Sesame (Kalo Til)',
    name_bn: 'কালো তিল',
    calories_per_100g: 573,
    protein_g: 17.7,
    carbs_g: 23,
    fat_g: 49,
    iron_mg: 14.6,
    calcium_mg: 975,
    folate_mcg: 97,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'general'],
    avoid_for: [],
  },
  {
    id: 'peanut',
    name_en: 'Peanut (Chingri Badam)',
    name_bn: 'চিনাবাদাম',
    calories_per_100g: 567,
    protein_g: 25.8,
    carbs_g: 16,
    fat_g: 49,
    iron_mg: 4.6,
    calcium_mg: 92,
    folate_mcg: 240,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['pregnancy', 'anaemia', 'general', 'adolescent'],
    avoid_for: ['gout'],
  },
  {
    id: 'chira',
    name_en: 'Flattened Rice (Chira)',
    name_bn: 'চিড়া',
    calories_per_100g: 346,
    protein_g: 7.1,
    carbs_g: 77,
    fat_g: 1.2,
    iron_mg: 2.8,
    calcium_mg: 10,
    folate_mcg: 7,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['child', 'general'],
    avoid_for: ['diabetes'],
  },
  {
    id: 'muri',
    name_en: 'Puffed Rice (Muri)',
    name_bn: 'মুড়ি',
    calories_per_100g: 402,
    protein_g: 7.9,
    carbs_g: 89,
    fat_g: 0.5,
    iron_mg: 3.4,
    calcium_mg: 6,
    folate_mcg: 5,
    season: ['all'],
    divisions: ['all'],
    price_tier: 'low',
    good_for: ['child', 'general'],
    avoid_for: ['diabetes'],
  },
]
